baseURL: 'https://raworlando.github.io/forgetmeblue/'
languageCode: en-us
title: ForgetMeBlue
theme: PaperMod
publishDir: docs

params:
  defaultTheme: auto # light dark
  disableThemeToggle: true

  homeInfoParams:
      Title: Welcome
      Content: to my blog. I am gonna write about what ever Ithink is imporant expect a post every month

  profileMode:
        enabled: true
        #title:  # optional default will be site title
        subtitle: "Where I get to write."
        imageUrl: "/images/Main_Flowers.jpeg" # optional
        imageWidth: 150 # custom size
        imageHeight: 150 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Posts
              url: "/post"
            - name: Stories
              url: "/stories"

  # socialIcons: # optional
  #     - name: "<platform>"
  #       url: "<link>"
  #     - name: "<platform 2>"
  #       url: "<link2>"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
